using System.Collections;
using System.Collections.Generic;
using ExitGames.Client.Photon.StructWrapping;
using UnityEngine;
using UnityEngine.SocialPlatforms;
using UnityEngine.Windows.WebCam;

public class CharacterInputHandler : MonoBehaviour
{
    // ï¿½Ã·ï¿½ï¿½Ì¾ï¿½ï¿½ï¿½ ï¿½Ô·ï¿½ï¿½ï¿½ Ã³ï¿½ï¿½ï¿½Ï°ï¿½ ï¿½ï¿½ ï¿½Ô·ï¿½ï¿½ï¿½ ï¿½ï¿½Æ®ï¿½ï¿½Å©ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½Ù¸ï¿½ ï¿½Ã·ï¿½ï¿½Ì¾ï¿½ï¿? ï¿½ï¿½ï¿½ï¿½È­ï¿½Ï±ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½Í¸ï¿½ ï¿½Øºï¿½
    // CharacterInputHandlerï¿½ï¿½ ï¿½Ã·ï¿½ï¿½Ì¾ï¿½Îºï¿½ï¿½ï¿? ï¿½Ô·ï¿½ï¿½ï¿½ ï¿½Þ¾ï¿½ LocalCameraHandlerï¿½ï¿½ NetworkInputDataï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½
    // ï¿½ï¿½ï¿½ï¿½Ú·Îºï¿½ï¿½ï¿? ï¿½Ìµï¿½, ï¿½ï¿½ï¿½ï¿½, Ä«ï¿½Þ¶ï¿½ È¸ï¿½ï¿½ ï¿½ï¿½ï¿½Ô·ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½
    // ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½Ã¿ï¿½ LocalCameraHandlerï¿½ï¿½ ï¿½Ù¸ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½Ò·ï¿? ï¿½ï¿½ï¿½ï¿½ï¿½Ï¿ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ Ä³ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½Ó°ï¿½ Ä«ï¿½Þ¶ï¿½ ï¿½ï¿½ï¿½ï¿½
    // GetNetworkInput() ï¿½Þ¼ï¿½ï¿½å¸¦ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½Æ®ï¿½ï¿½Å©ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½È­ï¿½ï¿½ ï¿½Ô·ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½(NetworkInputData)ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½Ï°ï¿½ ï¿½Ê±ï¿½È­

    Vector2 moveInputVector = Vector2.zero;
    Vector2 viewInputVector = Vector2.zero;
    bool isJumpButtonPressed = false;

    bool isShootingStart = false;

    //other components
    //CharacterMovementHandler characterMovementHandler;
    LocalCameraHandler localCameraHandler;
    CharacterMovementHandler characterMovementHandler;


    CharacterControl characterControl;
    private PoseEstimator poseEstimator;
    private PoseEstimationData poseEstimationData;
    // private bool goodEs;

    WebCamTexture webcamTexture;

    private void Awake(){
        //characterMovementHandler = GetComponent<CharacterMovementHandler>();
        localCameraHandler = GetComponentInChildren<LocalCameraHandler>();
        characterMovementHandler = GetComponent<CharacterMovementHandler>();    
    }

    // Start is called before the first frame update
    void Start()
    {
        // WebCamDevice[] devices = WebCamTexture.devices;
        
        /******************************************************************
            WebCamTextureï¿½ï¿½ ï¿½ï¿½ ï¿½ï¿½ ï¿½Ì»ï¿½ï¿½ï¿½ ï¿½ï¿½Å©ï¿½ï¿½Æ®ï¿½ï¿½ï¿½ï¿½ instantiate ï¿½ï¿½ ï¿½ï¿½ ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½Ï´ï¿½.
            PoseEstimator ï¿½ï¿½Å©ï¿½ï¿½Æ®ï¿½ï¿½ MonoBehaviorï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½Ïµï¿½ï¿½ï¿? ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½Å©ï¿½ï¿½Æ®ï¿½ï¿½
            ï¿½ï¿½ï¿½Æ°ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ poseEstimator.GetNetworkPoseData()ï¿½ï¿½ ï¿½Ö½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½Ò·ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½Ë´Ï´ï¿½.
        ******************************************************************/

        // webcamTexture = new WebCamTexture(devices[0].name, 640, 360, 60);

        // webcamTexture.Play();

        Cursor.lockState = CursorLockMode.Locked;
        Cursor.visible = false;
        characterControl = GetComponentInChildren<CharacterControl>();
        // pose estimator 
        poseEstimator = GetComponentInChildren<PoseEstimator>();

    }

    // Update is called once per frame
    void Update()
    {
        if(!characterMovementHandler.Object.HasInputAuthority)
            return;


        //View Input
        viewInputVector.x = Input.GetAxis("Mouse X");
        viewInputVector.y = Input.GetAxis("Mouse Y")*-1;

        //LocalCameraHandlerï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ Updateï¿½ï¿½ rotationï¿½ï¿½ ï¿½Æ´Ï¶ï¿½ ï¿½ï¿½Æ®ï¿½ï¿½Å©ï¿½ï¿½ aimï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½
        //characterMovementHandler.SetViewInputVector(viewInputVector);

        //Move Input
        //ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ syncï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿? ï¿½Æ·ï¿½Ã³ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½
        moveInputVector.x = Input.GetAxis("Horizontal");
        moveInputVector.y = Input.GetAxis("Vertical");

        //Shooting, jumpï¿½ï¿½ï¿½ï¿½ Updateï¿½ï¿½ GetNetworkInputï¿½ï¿½ sync ï¿½È¸Â¾ï¿½ ï¿½Æ·ï¿½Ã³ï¿½ï¿½ ï¿½Ò°ï¿½ï¿½ï¿½
        //isJumpButtonPressed = Input.GetButtonDown("Jump");
        //ï¿½Ì·ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½Ø¾ï¿½ï¿½ï¿½
        if(Input.GetButtonDown("Jump"))
            isJumpButtonPressed = true;

        //Set View
        localCameraHandler.SetViewInputVector(viewInputVector);
        if(poseEstimator!=null){
            poseEstimationData = poseEstimator.GetNetworkPoseData(); // good estimationï¿½ï¿½ï¿½ï¿½ È®ï¿½ï¿½ï¿½ï¿½ ï¿½Ê¿ï¿½ X
        }

        //Shooting °ü·Ã ÄÚµå if¹® ¾ÈÀÇ Á¶°ÇÀº º¯°æÇØ¾ßÇÔ
        if(Input.GetKeyDown(KeyCode.F)){
            isShootingStart = true;
        }
        
    }

    public NetworkInputData GetNetworkInput(){
        NetworkInputData networkInputData = new NetworkInputData();
        //View data
        //networkInputData.rotationInput = viewInputVector.x;

        //Aim data
        networkInputData.aimForwardVector = localCameraHandler.transform.forward;
        //Move data
        networkInputData.movementInput = moveInputVector;

        networkInputData.isJumpPressed = isJumpButtonPressed;
        networkInputData.poseData = poseEstimationData;
        // networkInputData.goodEstimate = goodEs; // good estimationï¿½ï¿½ï¿½ï¿½ È®ï¿½ï¿½ï¿½ï¿½ ï¿½Ê¿ï¿½ X
        

        networkInputData.isShootingStart = isShootingStart;
        
        isJumpButtonPressed = false;
        isShootingStart = false;
        return networkInputData;
    }


    public void SetPoseEstimator(PoseEstimator estimator) {
        poseEstimator = estimator;
    }

}
